//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPrj
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPurchaseItem
    {
<<<<<<< HEAD:MusicPrj/tPurchaseItem.cs
        public int fPurchaseItemID { get; set; }
        public string fCustomer { get; set; }
        public int fProductID { get; set; }
        public Nullable<System.DateTime> fDate { get; set; }
        public Nullable<decimal> fPrice { get; set; }
        public Nullable<int> fQuanity { get; set; }
        public Nullable<int> fisAlbum { get; set; }
        public Nullable<float> fDiscount { get; set; }
    
        public virtual tShoppingCart tShoppingCart { get; set; }
        public virtual tProduct tProduct { get; set; }
        public virtual tMember tMember { get; set; }
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tShoppingCart()
        {
            this.tPurchaseItems = new HashSet<tPurchaseItem>();
        }
    
        public int fCartID { get; set; }
        public string fCustomer { get; set; }
        public Nullable<System.DateTime> fDate { get; set; }
        public Nullable<decimal> fPrice { get; set; }
        public Nullable<int> fType { get; set; }
    
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchaseItem> tPurchaseItems { get; set; }
>>>>>>> 3f8fc7c0f3f2b90fde00f2155b735ad35c7fe8ae:MainWork/tShoppingCart.cs
    }
}
