//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbMusicStoreTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProjectMusicStoreEntities : DbContext
    {
        public dbProjectMusicStoreEntities()
            : base("name=dbProjectMusicStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAlbumType> tAlbumType { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
        public virtual DbSet<tProductKind> tProductKind { get; set; }
        public virtual DbSet<tShoppingCart> tShoppingCart { get; set; }
        public virtual DbSet<tAlbum> tAlbum { get; set; }
        public virtual DbSet<tProducts> tProducts { get; set; }
        public virtual DbSet<tPurchaseItem> tPurchaseItem { get; set; }
    }
}
